import {
  AlertTriangle,
  Banknote,
  Building2,
  Check,
  Clock,
  Combine,
  CreditCard,
  FilePlus,
  FileText,
  FileWarning,
  Hourglass,
  ListChecks,
  Mail,
  Package,
  RotateCcw,
  Send,
  ShieldCheck,
  TrendingUp,
  Triangle,
  User,
  Warehouse,
  X,
  type LucideIcon,
} from "lucide-react"

const ICONS: Record<string, LucideIcon> = {
  ret: RotateCcw,
  warn: AlertTriangle,
  clock: Clock,
  mail: Mail,
  cube: Package,
  alloc: ListChecks,
  cons: Combine,
  rate: TrendingUp,
  vendor: Building2,
  money: Banknote,
  surplus: Warehouse,
  expiry: Hourglass,
  appr: ShieldCheck,
  jcr: FileWarning,
  check: Check,
  card: CreditCard,
  doc: FileText,
  person: User,
  send: Send,
  x: X,
  docplus: FilePlus,
  tri: Triangle,
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? FileText
}
